codingDeps = [
  "bruno", # API explorer
  "cargo", # Rust package manager
  "dotnet-sdk_7", # SDK for .net
  "gcc", # C++ compiler
  "gdtoolkit_4", # Tools for gdscript
  "gnumake", # A tool to control the generation of non-source files from sources
  "nixfmt-rfc-style", # A nix formatter
  "nodejs", # Node package manager
  "python3", # Python
]

packages = [
  "appimage-run", # Appimage runner
  "bat", # Better cat command
  "bless", # HEX Editor
  "curtail", # Image compressor
  "duf", # Disk usage utility
  "efibootmgr", # Edit EFI entries
  "endeavour", # Tasks
  "fd", # Find alternative
  "fragments", # Bittorrent client following Gnome UI standards
  "gimp", # Image editor
  "gping", # ping with a graph
  "gthumb", # Image viewer
  "iotas", # Notes
  "jc", # JSON parser
  "jq", # JSON parser
  "killall", # Tool to kill all programs matching process name
  "lsd", # Better ls command
  "mission-center", # Task manager
  "moonlight-qt", # Remote streaming client
  "mousai", # Song recognizer
  "ncdu", # Terminal disk analyzer
  "newsflash", # RSS reader
  "nix-health", # Check system health
  "ntfs3g", # Support NTFS drives
  "obs-studio", # Recording/Livestream
  "onlyoffice-bin", # Microsoft Office alternative for Linux
  "p7zip", # 7zip
  "pavucontrol", # Sound manager
  "pitivi", # Video editor
  "rnnoise-plugin", # A real-time noise suppression plugin
  "scrcpy", # Remotely use android
  "signal-desktop", # Encrypted messaging platform
  "solaar", # Logitech devices manager
  "tree", # Display folder content at a tree format
  "unrar", # Support opening rar files
  "unzip", # An extraction utility
  "warp", # File sync
  "wget", # Terminal downloader
  "wine", # Compatibility layer capable of running Windows applications
  "winetricks", # Wine prefix settings manager
  "woeusb", # Windows ISO Burner
  "xorg.xhost", # Use x.org server with containers
  "yazi", # Terminal file manager
  "zenstates", # Ryzen CPU controller
]
