[icedos.applications]
extraPackages = []
aagl = false
android-tools = true
brave = true
celluloid = true
clamav = false
defaultBrowser = "zen" # Options: 'librewolf', 'zen'
defaultEditor = "zed" # Options: 'codium', 'zed'
falkor = false
fwupd = true
mysql = false
php = false
pitivi = false
protonvpn = true
rust = false
solaar = true
ssh = true
sunshine = true
suyu = false
walker = true
yazi = false

[icedos.applications.codium]
enable = true
zoomLevel = 0

[icedos.applications.httpd]
enable = false
php = true
user = "icedborn"

[icedos.applications.kitty]
enable = true
hideDecorations = false # Hide top bar

[icedos.applications.librewolf]
enable = false
privacy = true

[icedos.applications.librewolf.pwas]
enable = true
sites = [
  "https://app.tuta.com",
  "https://develop.element.io",
  "https://discord.com/app",
  "https://dtekteam.slack.com/",
  "https://web.skype.com/",
]

[icedos.applications.mangohud]
enable = true
maxFpsLimit = 144 # Use 0 for unlimited

[icedos.applications.mullvad]
enable = false
gui = false

[icedos.applications.obs-studio]
enable = true
virtualCamera = false

[icedos.applications.signal]
enable = true
package = "flare" # Options: 'flare', 'signal'

[icedos.applications.steam]
enable = true
beta = true
downloadsWorkaround = true

[icedos.applications.steam.session]
enable = true
user = "icedborn"

[icedos.applications.steam.session.autoStart]
enable = false
desktopSession = "hyprland"

[icedos.applications.tailscale]
enable = true
enableTrayscale = true

[icedos.applications.valent]
enable = false
deviceId = "901524a4_c7c0_407e_9903_431abce54131"

[icedos.applications.zed]
enable = true
ollamaSupport = false
vim = true

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zen-browser]
enable = true
privacy = true

[icedos.applications.zen-browser.pwas]
enable = true
sites = [
  "https://app.tuta.com",
  "https://develop.element.io",
  "https://discord.com/app",
  "https://dtekteam.slack.com/",
  "https://web.skype.com/",
]

[icedos.bootloader]
animation = true # Hides console and displays a loading interface based on OEM on boot

[icedos.bootloader.grub]
enable = false
device = "/dev/sda"

[icedos.bootloader.systemd-boot]
enable = true
mountPoint = "/boot"

[icedos.desktop]
accentColor = "7E57C2" # With gnome enabled this is getting overriden by gnome's selected accent color hex code

[icedos.desktop.autologin]
enable = true
user = "icedborn"

[icedos.desktop.gdm]
enable = true
autoSuspend = true

[icedos.desktop.gnome]
enable = false
accentColor = "purple" # Options: 'blue', 'teal', 'green', 'yellow', 'orange', 'red', 'pink', 'purple', 'slate'
hotCorners = false
powerButtonAction = "interactive"
startupItems = false

# Options: 'minimize', 'maximize', 'close', 'spacer'(adds space between buttons), ':'(left-center-right separator)
titlebarLayout = "appmenu:close"

[icedos.desktop.gnome.extensions]
arcmenu = false
dashToPanel = false

[icedos.desktop.gnome.clock]
date = false # Show the month and day of the month on the clock
weekday = false # Show the day of the week on the clock

[icedos.desktop.gnome.workspaces]
dynamicWorkspaces = true
maxWorkspaces = 1 # Determines the maximum number of workspaces when dynamic workspaces are disabled

[icedos.desktop.hyprland]
enable = true
followMouse = 1 # Options: https://wiki.hyprland.org/Configuring/Variables/#follow-mouse-cursor
hyprspace = true

startupScript = """
run protonvpn-app
run zen
run zen-pwas
nautilus -w &
nautilus -w &
run steam
run flare
run zeditor
kitty --class task-managers btop &
kitty --class terminals tmux new -s terminals \\; split-window -v \\; select-pane -U \\; split-window -h \\; select-pane -D &
"""

windowRules = [
  "workspace 1 silent, class:^(zen)$",
  "workspace 2 silent, class:^(dev.zed.Zed)$",
  "workspace 3 silent, class:^(steam_app_.*)$, title:^((?!notificationtoasts.*).)*$",
  "workspace 11 silent, class:^(de.schmidhuberj.Flare|pwas)$",
  "workspace 12 silent, class:^(Steam|steam)$, title:^((?!notificationtoasts.*).)*$",
  "workspace 12 silent, title:^(.*Steam[A-Za-z0-9\\s]*)$",
  "workspace 13 silent, class:^(org\\.gnome\\.Nautilus)$",
  "workspace 14 silent, class:^(task-managers)$",
  "workspace 15 silent, class:^(terminals)$",
]

[icedos.desktop.hyprland.cs2fix]
enable = false
width = 1440
height = 1080

[icedos.desktop.hyprland.hyproled]
enable = false
startWidth = 0
startHeight = 0
endWidth = 3440
endHeight = 1440

[icedos.desktop.hyprland.lock]
secondsToLowerBrightness = 60
cpuUsageThreshold = 60 # CPU usage to inhibit lock in percentage
diskUsageThreshold = 10 # Disk usage to inhibit lock in MB/s
networkUsageThreshold = 1_000_000 # Network usage to inhibit lock in bytes/s

[icedos.hardware]
bluetooth = true
mounts = true # Set to false if hardware/mounts.nix is not correctly configured

[icedos.hardware.btrfs.compression]
enable = true
mounts = true # Use btrfs compression for mounted drives
root = true # Use btrfs compression for / (root)

[icedos.hardware.cpus]
intel = false

[icedos.hardware.cpus.amd]
enable = true

[icedos.hardware.cpus.amd.undervolt]
enable = true
value = "-p 0 -v 3C -f A0" # Pstate 0, 1.175 voltage, 4000 clock speed

[icedos.hardware.devices]
laptop = false
steamdeck = false

[icedos.hardware.drivers]
rtl8821ce = false # Use the unofficial RTL8821CE driver
xpadneo = true # Xbox gamepad bluetooth driver (supports various xinput controllers)

[icedos.hardware.devices.server]
enable = false
dns = "9.9.9.9"
gateway = "192.168.1.1"
interface = "eno1"
ip = "192.168.1.3"

[icedos.hardware.gpus.amd]
enable = true
rocm = true

[icedos.hardware.gpus.nvidia]
enable = false
beta = false
cuda = false
openDrivers = true

[icedos.hardware.gpus.nvidia.powerLimit]
enable = true
value = 242

[[icedos.hardware.monitors]]
name = "DP-1"
resolution = "3440x1440"
refreshRate = 144
position = "0x0"
scaling = 1
rotation = 0
tenBit = true

[[icedos.hardware.monitors]]
name = "DP-2"
resolution = "1920x1080"
refreshRate = 144
position = "3440x0"
scaling = 1
rotation = 0
tenBit = true

[[icedos.hardware.monitors]]
name = "HDMI-A-1"
resolution = "3840x2160"
refreshRate = 60
position = "-3840x0"
scaling = 1
rotation = 0
tenBit = true

[icedos.hardware.networking]
hostname = "desktop"
hosts = false
ipv6 = false

[icedos.system]
channels = [] # https://github.com/NixOS/nixpkgs/branches/active
forceFirstBuild = false
home = "/home"
kernel = "cachyos" # Options: 'cachyos', 'cachyos-server', 'latest', 'lts', 'valve', 'zen'
swappiness = 1
version = "23.05" # Do not change without checking the docs (config.system.stateVersion)

[icedos.system.generations]
bootEntries = 10

[icedos.system.generations.garbageCollect]
automatic = true
days = 0 # Number of days before a generation can be deleted
generations = 10 # Number of generations that will always be kept
interval = "Mon *-*-* 00:00:00" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)

[icedos.system.users.icedborn]
description = "IceDBorn"
type = "main" # Options: 'main', 'work', 'server'

[icedos.system.users.icedborn.applications.codium]
autoSave = "off" # Options: 'off', 'afterDelay', 'onFocusChange', 'onWindowChange'
formatOnSave = true
formatOnPaste = true

[icedos.system.users.icedborn.applications.git]
username = "IceDBorn"
email = "git.outsider841@simplelogin.fr"

[icedos.system.users.icedborn.desktop.gnome.pinnedApps.arcmenu]
enable = false
list = ["codiumIDE.desktop", "codium.desktop", "mullvad-vpn.desktop"]

# Set pinned apps for gnome shell (will be used by dash-to-panel if enabled)
[icedos.system.users.icedborn.desktop.gnome.pinnedApps.shell]
enable = false
list = [
  "steam.desktop",
  "webcord.desktop",
  "signal-desktop.desktop",
  "librewolf.desktop",
]

[icedos.system.users.icedborn.desktop.idle.lock]
enable = true
seconds = 180

[icedos.system.users.icedborn.desktop.idle.disableMonitors]
enable = true
seconds = 900

[icedos.system.users.icedborn.desktop.idle.suspend]
enable = true
seconds = 1800

[icedos.system.virtualisation]
libvirtd = false # A daemon that manages virtual machines
waydroid = false # Android container

[icedos.system.virtualisation.containerManager]
enable = false
usePodman = true
requireSudoForDocker = true # CAUTION: Disabling this gives every user root priviledges!
